package media

import (
	"context"
	"errors"
	"fmt"
	"io"
	"mime"
	"time"

	nanoid "github.com/jaevor/go-nanoid"
)

// ErrNotFound is returned by Get when the requested storage key does not exist.
var ErrNotFound = errors.New("media: object not found")

// MediaStore is the pluggable storage backend for user-uploaded media.
// Implementations must be safe for concurrent use.
//
// Keys are opaque strings generated by StorageKey. Callers must treat them as
// opaque — do not parse or construct keys outside this package.
type MediaStore interface {
	// Put stores the content addressed by key. If a value already exists at
	// key it is overwritten (same key always means the same content).
	Put(ctx context.Context, key string, r io.Reader, contentType string) error

	// Get returns a streaming reader for the stored object.
	// The caller is responsible for closing the returned ReadCloser.
	// Returns ErrNotFound if the key does not exist.
	Get(ctx context.Context, key string) (io.ReadCloser, error)

	// Delete removes the object at key. A no-op if the key does not exist.
	Delete(ctx context.Context, key string) error

	// URL returns the public URL at which the object can be fetched.
	// For the local driver this is a path under MEDIA_BASE_URL.
	// For S3 without a CDN this is a presigned GetObject URL.
	URL(ctx context.Context, key string) (string, error)
}

// Config holds the fields the media factory needs.
// Constructed by serve.go from *config.Config.
type Config struct {
	Driver     string // "local" | "s3"
	LocalPath  string // required when Driver == "local"
	BaseURL    string // required — public base URL for local and S3
	S3Bucket   string // required when Driver == "s3"
	S3Region   string // required when Driver == "s3"
	S3Endpoint string // optional: endpoint override for MinIO / R2 / B2
	CDNBase    string // optional: CDN prefix; if set, URL() returns CDN URL instead of presigned
	MaxBytes   int64  // maximum upload size in bytes (from MEDIA_MAX_BYTES)
}

// DriverFunc is a constructor for a MediaStore implementation.
// Drivers register themselves via Register.
type DriverFunc func(cfg Config) (MediaStore, error)

var drivers = map[string]DriverFunc{}

// Register registers a MediaStore driver by name. Called from driver packages in init().
func Register(name string, fn DriverFunc) {
	drivers[name] = fn
}

// New returns the MediaStore implementation selected by cfg.Driver.
// Driver packages (local, s3) must be imported for side-effect registration
// before calling New (e.g. in serve.go: _ "github.com/.../media/local").
func New(cfg Config) (MediaStore, error) {
	driver := cfg.Driver
	if driver == "" {
		driver = "local"
	}
	fn, ok := drivers[driver]
	if !ok {
		return nil, fmt.Errorf("media: unknown driver %q (valid: local, s3)", cfg.Driver)
	}
	if driver == "local" && cfg.LocalPath == "" {
		return nil, errors.New("media: MEDIA_LOCAL_PATH is required when MEDIA_DRIVER=local")
	}
	if driver == "s3" && (cfg.S3Bucket == "" || cfg.S3Region == "") {
		return nil, errors.New("media: MEDIA_S3_BUCKET and MEDIA_S3_REGION are required when MEDIA_DRIVER=s3")
	}
	return fn(cfg)
}

// nanoidGen is a package-level nanoid generator (URL-safe alphabet, 21 chars).
// Initialised once; safe for concurrent use.
var nanoidGen func() string

func init() {
	var err error
	nanoidGen, err = nanoid.Standard(21)
	if err != nil {
		panic("media: failed to initialise nanoid generator: " + err.Error())
	}
}

// StorageKey generates a date-sharded, collision-resistant storage key for
// an uploaded file.
//
// Format: {year}/{month}/{day}/{nanoid}{ext}
// Example: 2026/02/24/V1StGXR8_Z5jdHi6B-myT.jpg
func StorageKey(contentType string) string {
	now := time.Now().UTC()
	ext := extensionForContentType(contentType)
	id := nanoidGen()
	return fmt.Sprintf("%04d/%02d/%02d/%s%s",
		now.Year(), now.Month(), now.Day(), id, ext)
}

var preferredExtensions = map[string]string{
	"image/jpeg": ".jpg",
	"image/png":  ".png",
	"image/gif":  ".gif",
	"image/webp": ".webp",
	"video/mp4":  ".mp4",
	"video/webm": ".webm",
	"audio/mpeg": ".mp3",
	"audio/ogg":  ".ogg",
}

// extensionForContentType returns the canonical file extension for the given
// MIME type. Falls back to mime database or empty string for unknown types.
func extensionForContentType(ct string) string {
	if ext, ok := preferredExtensions[ct]; ok {
		return ext
	}
	exts, _ := mime.ExtensionsByType(ct)
	if len(exts) > 0 {
		return exts[0]
	}
	return ""
}

// AllowedContentTypes is the set of MIME types accepted at upload time.
var AllowedContentTypes = map[string]string{
	"image/jpeg": "image",
	"image/png":  "image",
	"image/gif":  "gifv",
	"image/webp": "image",
	"video/mp4":  "video",
	"video/webm": "video",
	"audio/mpeg": "audio",
	"audio/ogg":  "audio",
}
