ALTER TABLE user_filters ADD COLUMN phrase TEXT NOT NULL DEFAULT '';
ALTER TABLE user_filters ADD COLUMN whole_word BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_filters ADD COLUMN irreversible BOOLEAN NOT NULL DEFAULT FALSE;
